/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

/**
 *
 * @author Evandro
 */
public class LoginView extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public LoginView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        usernameInput = new javax.swing.JTextField();
        passwordInput = new javax.swing.JPasswordField();
        jLabelusernameLabel = new javax.swing.JLabel();
        jLabelpasswordLabel = new javax.swing.JLabel();
        jLabelTitleLogin = new javax.swing.JLabel();
        jLabelbackgroundPanelLogin = new javax.swing.JLabel();
        jLabelbackgroundLogin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        usernameInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameInputActionPerformed(evt);
            }
        });
        getContentPane().add(usernameInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 430, 290, 40));
        getContentPane().add(passwordInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 530, 290, 40));

        jLabelusernameLabel.setBackground(new java.awt.Color(0, 0, 0));
        jLabelusernameLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelusernameLabel.setForeground(new java.awt.Color(255, 255, 255));
        jLabelusernameLabel.setText("Usuário");
        jLabelusernameLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabelusernameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 400, -1, -1));

        jLabelpasswordLabel.setBackground(new java.awt.Color(0, 0, 0));
        jLabelpasswordLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelpasswordLabel.setForeground(new java.awt.Color(255, 255, 255));
        jLabelpasswordLabel.setText("Senha");
        jLabelpasswordLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabelpasswordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 500, -1, -1));

        jLabelTitleLogin.setBackground(new java.awt.Color(0, 0, 0));
        jLabelTitleLogin.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabelTitleLogin.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitleLogin.setText("Login");
        jLabelTitleLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabelTitleLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 270, -1, -1));

        jLabelbackgroundPanelLogin.setBackground(new java.awt.Color(255, 255, 255));
        jLabelbackgroundPanelLogin.setIcon(new javax.swing.ImageIcon("C:\\Users\\Evandro\\Documents\\NetBeansProjects\\barbershop\\src\\main\\java\\View\\imagens\\painel-login.png")); // NOI18N
        getContentPane().add(jLabelbackgroundPanelLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, 540, 460));

        jLabelbackgroundLogin.setIcon(new javax.swing.ImageIcon("C:\\Users\\Evandro\\Documents\\NetBeansProjects\\barbershop\\src\\main\\java\\View\\imagens\\Logo.jpg")); // NOI18N
        getContentPane().add(jLabelbackgroundLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, -10, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usernameInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameInputActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelTitleLogin;
    private javax.swing.JLabel jLabelbackgroundLogin;
    private javax.swing.JLabel jLabelbackgroundPanelLogin;
    private javax.swing.JLabel jLabelpasswordLabel;
    private javax.swing.JLabel jLabelusernameLabel;
    private javax.swing.JPasswordField passwordInput;
    private javax.swing.JTextField usernameInput;
    // End of variables declaration//GEN-END:variables
}
